/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akinatoranimales.interfaz;

import akinatoranimales.Archivos;
import akinatoranimales.Partida;
import akinatoranimales.estructuras.ArbolDecision;
import akinatoranimales.estructuras.Decision;
import akinatoranimales.estructuras.NodoArbol;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author dayan
 */
public class Inicio extends javax.swing.JFrame {
    private ArbolDecision baseConocimientos;
    private Partida partida;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdivinar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();
        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        btnVaciarBase = new javax.swing.JButton();
        btnCargarBase = new javax.swing.JButton();
        btnGuardarBase = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        btnVerBC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdivinar.setText("Adivinar Animal");
        btnAdivinar.setEnabled(false);
        btnAdivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinarActionPerformed(evt);
            }
        });

        output.setEditable(false);
        output.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(output);

        btnSi.setText("SI");
        btnSi.setEnabled(false);
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        btnNo.setText("NO");
        btnNo.setEnabled(false);
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        btnVaciarBase.setText("Inicializar Base de Conocimientos");
        btnVaciarBase.setEnabled(false);
        btnVaciarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarBaseActionPerformed(evt);
            }
        });

        btnCargarBase.setText("Cargar Base de Conocimientos");
        btnCargarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarBaseActionPerformed(evt);
            }
        });

        btnGuardarBase.setText("Guardar Base de Conocimiento");
        btnGuardarBase.setEnabled(false);
        btnGuardarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarBaseActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar animal");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        btnVerBC.setText("Ver Base de conocimientos");
        btnVerBC.setEnabled(false);
        btnVerBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerBCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerBC))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdivinar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVaciarBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargarBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarBase)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdivinar)
                    .addComponent(btnVaciarBase)
                    .addComponent(btnCargarBase)
                    .addComponent(btnGuardarBase))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSi)
                            .addComponent(btnNo)
                            .addComponent(btnVerBC))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Buscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarBaseActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setFileFilter(new FileNameExtensionFilter("Archivos csv", "csv"));
            chooser.showOpenDialog(this);
            File selectedFile = chooser.getSelectedFile();
            if (selectedFile != null) {
                String contenido = Archivos.cargar(selectedFile.getAbsolutePath());
                setBaseConocimientos(ArbolDecision.desdeCsv(contenido));
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error abriendo archivo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarBaseActionPerformed

    private void btnAdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinarActionPerformed
        iniciarJuego();
    }//GEN-LAST:event_btnAdivinarActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        imprimirSi();
        emitirRespuesta(Decision.SI);
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        imprimirNo();
        emitirRespuesta(Decision.NO);
    }//GEN-LAST:event_btnNoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String animal = JOptionPane.showInputDialog("Ingrese animal a buscar");
            if (animal != null && !animal.isBlank()) {
                NodoArbol existe = baseConocimientos.buscar(animal);
                if (existe != null){
                    JOptionPane.showMessageDialog(this, "El animal si se encuentra");
                }
                else{
                    JOptionPane.showMessageDialog(this, "el animal no se encuentra");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "debes nombrar un animal");
            }
    }//GEN-LAST:event_BuscarActionPerformed

    private void btnVerBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerBCActionPerformed
        String styleSheet =
 		"node {" +
                "   size-mode: fit;" +
                "   shape: box;" +
                "   fill-color: white;" +
                "   stroke-mode: plain;" +
                "   padding: 3px, 2px;" +
 		"}";
	System.setProperty("org.graphstream.ui", "swing");
	Graph graph = new SingleGraph("Base de Conocimientos");
	graph.setAttribute("ui.stylesheet", styleSheet);

	mostrarArbol(baseConocimientos.getRaiz(), graph, 0);
        JOptionPane.showMessageDialog(this, "Se recomienda arrastrar los nodos para obtener una mejor visaualización");
	Viewer viewer = graph.display();
	viewer.disableAutoLayout();
        viewer.setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
    }//GEN-LAST:event_btnVerBCActionPerformed

    private void btnVaciarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarBaseActionPerformed
        baseConocimientos.vaciar();
        setBaseConocimientos(null);
    }//GEN-LAST:event_btnVaciarBaseActionPerformed

    private void btnGuardarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarBaseActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setFileFilter(new FileNameExtensionFilter("Archivos csv", "csv"));
            chooser.showOpenDialog(this);
            File selectedFile = chooser.getSelectedFile();
            if (selectedFile != null) {
                String contenidos = baseConocimientos.aCsv();
                Archivos.guardar(selectedFile.getAbsolutePath(), contenidos);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error abriendo archivo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarBaseActionPerformed
    
    private void iniciarJuego() {
        btnSi.setEnabled(true);
        btnNo.setEnabled(true);
        partida = new Partida(baseConocimientos);
        partida.iniciar();
        output.setText("<html><head></head><body><p style=\"margin-top: 0\"></p></body></html>");
        imprimirNeutro("Partida iniciada!");
        imprimirNeutro(partida.getSiguientePregunta());       
    }
    
    private void imprimirSi() {
        imprimir("Si", Color.GREEN);
    }
    
    private void imprimirNo() {
        imprimir("No", Color.RED);
    }
    
    private void imprimirNeutro(String mensaje) {
        imprimir(mensaje, Color.BLACK);
    }
    
    private void imprimir(String mensaje, Color color) {
        String textoActual = output.getText();
        String toPrint = textoActual.replace("</body>", "<span style=\"color: #" + colorAHex(color) + "\">" + mensaje + "</span><br></body>");
        output.setText(toPrint);
        System.out.println(toPrint);
    }
    
    public void setBaseConocimientos(ArbolDecision baseConocimientos) {
        this.baseConocimientos = baseConocimientos;
        btnAdivinar.setEnabled(this.baseConocimientos != null);
        btnVaciarBase.setEnabled(this.baseConocimientos != null);
        btnGuardarBase.setEnabled(this.baseConocimientos != null);
        btnVerBC.setEnabled(this.baseConocimientos != null);
    }
    
    private String colorAHex(Color color) {
        return Integer.toHexString(color.getRGB()).substring(2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton btnAdivinar;
    private javax.swing.JButton btnCargarBase;
    private javax.swing.JButton btnGuardarBase;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnVaciarBase;
    private javax.swing.JButton btnVerBC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane output;
    // End of variables declaration//GEN-END:variables

    private void emitirRespuesta(Decision decision) {
        partida.responder(decision);
        if (partida.getFinalizada()) {
            Color color = partida.getVictoria() 
                    ? Color.GREEN
                    : Color.RED;
            String mensajeFin = partida.getVictoria()
                    ? "He adivinado! Mis poderes son inigualables"
                    : "Vaya... parece que he fracasado...";
            imprimir(mensajeFin, color);
            if (!partida.getVictoria()) {
                 iniciarSecuenciaRetroalimentacion();
            }
        } else {
            String siguientePregunta = partida.getSiguientePregunta();
            imprimirNeutro(siguientePregunta);
        }
    }
    
    private void iniciarSecuenciaRetroalimentacion() {
        String nuevoAnimal = JOptionPane.showInputDialog(this, "¿En qué animal estabas pensando?", "Retroalimentación", JOptionPane.INFORMATION_MESSAGE);
        if (nuevoAnimal == null || nuevoAnimal.isBlank()) {
            JOptionPane.showMessageDialog(this, "Secuencia de retroalimentación abortada");
            return;
        }
        if (baseConocimientos.buscar(nuevoAnimal) != null) {
            JOptionPane.showMessageDialog(this, "Ese animal ya existe!!", "Tratas de engañarme?", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        String ultimoAnimal = partida.getSiguientePregunta();
        String nuevaPregunta = JOptionPane.showInputDialog(this, "¿Qué diferencia a un " + nuevoAnimal + " de un " + ultimoAnimal + "?", "Retroalimentación", JOptionPane.INFORMATION_MESSAGE);
        if (nuevaPregunta == null || nuevaPregunta.isBlank()) {
            JOptionPane.showMessageDialog(this, "Secuencia de retroalimentación abortada");
            return;
        }
        Decision decision = (Decision) JOptionPane.showInputDialog(this, "¿Si el animal fuese " + nuevoAnimal + ", cuál sería la respuesta a la pregunta?", "Retroalimentación", JOptionPane.QUESTION_MESSAGE, null, Decision.values(), Decision.SI);
        String ultimaPregunta = partida.getPreguntaAnterior();
        Decision decisionAnterior = partida.getDecisionAnterior();
        baseConocimientos.insertar(nuevaPregunta, ultimaPregunta, decisionAnterior);
        baseConocimientos.insertar(nuevoAnimal, nuevaPregunta, decision);
        baseConocimientos.insertar(ultimoAnimal, nuevaPregunta, decision.negado());
        JOptionPane.showMessageDialog(this, "Nuevo animal agregado: " + nuevoAnimal, "¡Gracias! Ahora soy más inteligente", JOptionPane.PLAIN_MESSAGE);
    }
    
    private void mostrarArbol(NodoArbol nodo, Graph grafo, double x) {
        if (nodo == null) {
            return;
        }
        String etiqueta = nodo.getEtiqueta();
        Node n = grafo.addNode(etiqueta);
        int profundidad = baseConocimientos.profundidad(etiqueta);
        int grado = baseConocimientos.grado();
        n.setAttribute("ui.label", etiqueta);
        n.setAttribute("x", x);
        n.setAttribute("y", profundidad * -1);
        mostrarArbol(nodo.getNo(), grafo, x - (2d / ((double)(profundidad))));
        mostrarArbol(nodo.getSi(), grafo, x + (2d / ((double)(profundidad))));
        
        if (nodo.getNo() != null) {
            String etiquetaNo = nodo.getNo().getEtiqueta();
            Edge e = grafo.addEdge(etiqueta + etiquetaNo, etiqueta, etiquetaNo);
            e.setAttribute("ui.label", "No");
        }
        
        if (nodo.getSi() != null) {
            String etiquetaSi = nodo.getSi().getEtiqueta();
            Edge e = grafo.addEdge(etiqueta + etiquetaSi, etiqueta, etiquetaSi);
            e.setAttribute("ui.label", "Si");
        }
    }
}